### ISSUE TITLE
Concurrent Test executions invoke a ResolutionError from the jsii/kernel about a circular dependency

### ISSUE THREAD

**Issue by ttomtsis** [ttomtsis/icarus#18]
## This bug is related to the StackDeployer class in the util.terraform package

When icarus services a single Test execution request, it also deploys to the cloud provider ( Lambda or GCF ) the function that is associated with that test.

Functions are deployed using the Terraform CDK for Java, in essence for every function at least one terraform stack is created and deployed.

When multiple Test requests arrive at the same time, multiple applications are synthesized, each containing a single stack.

 **No shared state exists between requests, and no visible race conditions could be identified.**
 
 Despite that, the terraform CDK seems to be creating correlations between  the synthesized stacks.
 
 For example when deploying demoFunction-be813 and demoFunction-b98fb , the following error can be seen:
 
 ```

 java.lang.RuntimeException: Error: Resolution error: Can not add dependency demoFunction-be813 to demoFunction-b98fb since it would result in a loop.
Object creation stack:
  at new Intrinsic (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tokens\private\intrinsic.js:22:66)
  at new TFExpression (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tfExpression.js:11:1)
  at new Reference (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tfExpression.js:111:9)
  at ref (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tfExpression.js:147:12)
  at S3Bucket.interpolationForAttribute (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\terraform-resource.js:140:39)
  at S3Bucket.getStringAttribute (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\terraform-resource.js:36:45)
  at get id [as id] (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\@cdktf\provider-aws\lib\s3-bucket\index.js:2836:21)
  at C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:9825:188
  at Kernel._Kernel_ensureSync (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:10480:24)
  at Kernel.get (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:9825:104)
  at KernelHost.processRequest (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11699:36)
  at KernelHost.run (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11659:22)
  at Immediate._onImmediate (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11660:46)
  at process.processImmediate (node:internal/timers:476:21)
@jsii/kernel.RuntimeError: Error: Resolution error: Can not add dependency demoFunction-be813 to demoFunction-b98fb since it would result in a loop.
Object creation stack:
  at new Intrinsic (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tokens\private\intrinsic.js:22:66)
  at new TFExpression (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tfExpression.js:11:1)
  at new Reference (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tfExpression.js:111:9)
  at ref (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\tfExpression.js:147:12)
  at S3Bucket.interpolationForAttribute (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\terraform-resource.js:140:39)
  at S3Bucket.getStringAttribute (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\cdktf\lib\terraform-resource.js:36:45)
  at get id [as id] (C:\Users\tomto\AppData\Local\Temp\jsii-kernel-wL2ZbG\node_modules\@cdktf\provider-aws\lib\s3-bucket\index.js:2836:21)
  at C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:9825:188
  at Kernel._Kernel_ensureSync (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:10480:24)
  at Kernel.get (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:9825:104)
  at KernelHost.processRequest (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11699:36)
  at KernelHost.run (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11659:22)
  at Immediate._onImmediate (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11660:46)
  at process.processImmediate (node:internal/timers:476:21)
    at Kernel._Kernel_ensureSync (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:10491:23)
    at Kernel.invoke (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:9855:102)
    at KernelHost.processRequest (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11699:36)
    at KernelHost.run (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11659:22)
    at Immediate._onImmediate (C:\Users\tomto\AppData\Local\Temp\jsii-java-runtime4284538135721879973\lib\program.js:11660:46)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by ttomtsis** [comment]
This issue has been temporarily patched up by moving the app.synth() inside a synchronized method.

However this approach incurs serious performance drawbacks and should be avoided.
